### ISSUE TITLE
FlushMetrics::onTerminate during commands

### ISSUE THREAD

**Issue by adrienbrault** [beberlei/metrics#24]
It should be as simple as listening on the `console.terminate` event

**Comment by stof** [comment]
@lyrixx it may be good to fix it for 1.x too

**Comment by lyrixx** [comment]
So I have to create a branch for that. I will try to do it asap (but i can not promise anything).
I re-open the issue for 1.X branch.

**Comment by lyrixx** [comment]
Closing, as the 1.X branch is not supported. If someone want it, please re-open the issue.
