### ISSUE TITLE
Add support for tagging metrics?

### ISSUE THREAD

**Issue by Shyru** [beberlei/metrics#34]
First, great library, I just thought about implementing something similar to prevent vendor lock-in.
For now we will use datadog for our metric needs.
StatsD (Datadog) supports adding arbitrary tags to metrics. Could that be added on the Collector API level with the default that other Collectors would not support tags? Or perhaps there are even more collectors that also support tags and could be enhanced to support tags.
If we would make the parameter tags optional with an empty default value it would also be backwards compatible for all users of the library. Only the collectors would need to be modified to account for the new parameter.
What do you think?
(I would gladly implement this if there is a chance to include this, otherwise I will probably create my own fork)

**Comment by lyrixx** [comment]
Yes, it seems a good idea. Could you send a PR ?

**Comment by Shyru** [comment]
Yes I will try to implement that and create a pull request over the coming days.

**Comment by eexit** [comment]
@Shyru hey, any update on this?

**Comment by kimmelserj** [comment]
Perhaps, this feature is implemented in #48.

**Comment by gabel** [comment]
@Shyru Any news on that topic? Did you already wrote a DatadogStatsD Adapter for metric?

**Comment by eexit** [comment]
@Shyru @lyrixx @kimmelserj Maybe somebody wants to review #51?

**Comment by eexit** [comment]
I believe this issue could be closed :)

**Comment by lyrixx** [comment]
@eexit Yes, Thanks.
