### ISSUE TITLE
Symfony 4 compatibility

### ISSUE THREAD

**Issue by nicoschoenmaker** [beberlei/metrics#58]
When using this library in Symfony 4, you get the following error
```
Fatal error: Uncaught Error: Class 'Symfony\Component\DependencyInjection\DefinitionDecorator'
not found in vendor/beberlei/metrics/src/Beberlei/Bundle/MetricsBundle/DependencyInjection/BeberleiMetricsExtension.php
on line 39
```

In the Symfony 4.0 upgrade guide there is a note:
```
The DefinitionDecorator class has been removed. Use the ChildDefinition class instead.
```
Problem: The alternative (`ChildDefinition`) was introduced in Symfony 3.3, but this package appears to support earlier versions.

So we should either up the minimal requirement to 3.3 (or 4.0?), or do some kind of `class_exists` hack. Preferences?

**Comment by lyrixx** [comment]
Could you submit a PR? If not, I could do it ;)

**Comment by nicoschoenmaker** [comment]
@lyrixx I was not sure on the solution, but I would love feedback on #59 (proper fix) and/or #60 (hotfix) :smile:

**Comment by lyrixx** [comment]
I will merge #60 first, tag a new release, then merge #59. What do you think ?

**Comment by nicoschoenmaker** [comment]
#60 is a non-bc break, merging & tagging that would be great. That will allow people to upgrade :+1:

Following up with #59 would be good for the maintainability, since it will fix that broken build.

**Comment by nicoschoenmaker** [comment]
@lyrixx any update on this? What you initially suggested looks like a good idea to me :)

**Comment by lyrixx** [comment]
Sorry, I was :skier: :)

**Comment by lyrixx** [comment]
v2.6.0 released :tada:

**Comment by nicoschoenmaker** [comment]
Hehe, np. Thanks for the merge. Hope you had a great time :ski:
