### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by chucky2305** [beberlei/metrics#67]
I have read the docs, code and tests multiple times but i cant really understand it.

In my code i have this

```
$counter = $registry->getOrRegisterCounter('app_name', 'max', 'helptext');
$counter->incBy(1);
```

This should add a counter called "max" right?

For simplicity, lets say, that this is my only metric i want to have.

How can i export / display / get all the metrics (in this case only one) to make them public under a certain route like `/metric`?

**Comment by lyrixx** [comment]
Hello.

This lib is an abstraction of "Collector" That will publish "metrics" in some metrics database like statsD, Graphite ...

There is nothing here to visualize metrics.
